/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.recruitai.controller; import cn.zhuatech.recruitai.common.ApiResponse; import cn.zhuatech.recruitai.service.CandidateMatchService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; /**
                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                            */
@RestController @RequestMapping("/api/ai") @PreAuthorize("hasAnyRole('DOMAIN_USER','DOMAIN_OPERATOR','ADMIN')") public class AiFeatureController { private final CandidateMatchService service; /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
public AiFeatureController(CandidateMatchService service){this.service=service;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/candidate/match") public ApiResponse<CandidateMatchService.Result> execute(@Valid @RequestBody CandidateMatchService.Request request){return ApiResponse.ok("候选人与职位可解释匹配完成",service.match(request));} }